[profile.default]
#solc = "0.8.30"
auto_detect_solc = true
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 100
evm_version = "prague"

remappings = [
    "canonical-weth=node_modules/canonical-weth",
    "@gnosis.pm=node_modules/@gnosis.pm",
    "@prb=node_modules/@prb",
    "@uniswap=node_modules/@uniswap",
    "wormhole-solidity-sdk=node_modules/wormhole-solidity-sdk",
]
